### ISSUE TITLE
API request to convert bytearray to bitmap

### ISSUE THREAD

**Issue by jpyo0613** [UdaraWanasinghe/webp-android#2]
Hello!!
I'm looking for a quick way to decode a bytearray to a webp image using ndk on Android.
I just found your project! thank you
However, there is no API to convert bytearray to bitmap. Do you have any plans to make one?

**Comment by UdaraWanasinghe** [comment]
It will be added soon.

**Comment by jpyo0613** [comment]
Wow! Thank you!!
