### ISSUE TITLE
encode gif to anim webp 

### ISSUE THREAD

**Issue by zubinxiong** [UdaraWanasinghe/webp-android#5]
- Hi, I'm trying this project and find some problem about encode bitmap to anim webp.
- I am using it to convert gif to anim webp, but the result webp seems different with with the picture by using https://ezgif.com/gif-to-webp/ , I'm trying to use webpinfo to see the different , then i find ANMF seems different. this library generate the webp some ANMF dispose and blend different. the output image look same in browser but some app like whatsapp you will find the image has some different look, there has some frame line just 1 or 2 pixel in the bottom . the flowing file is the origin gif and code.

```Kotlin
val webPAnimEncoder = WebPAnimEncoder(width = 512, height = 512,
                    options = WebPAnimEncoderOptions(
                        minimizeSize = true,
                        animParams = WebPMuxAnimParams(
                            backgroundColor = Color.TRANSPARENT,
                            loopCount = 0
                        )
                    )
                )

 webPAnimEncoder.configure(
                    config = WebPConfig(
                        lossless = WebPConfig.COMPRESSION_LOSSY
                    ),
                    preset = WebPPreset.WEBP_PRESET_PICTURE
                )

 val gifDrawable = GifDrawable(source.file)
                var time = 0L
                for (i in 0 until gifDrawable.numberOfFrames) {
                    val bitmap = gifDrawable.seekToFrameAndGet(i)
                    val width = bitmap.width
                    val height = bitmap.height

                    val scaleWidth = (512.0 / width).toFloat()
                    val scaleHeight = (512.0 / height).toFloat()

                    val matrix = Matrix()
                    matrix.postScale(scaleWidth, scaleHeight)
                    val resizeBitmap = Bitmap.createBitmap(bitmap, 0, 0, width, height, matrix, true)
                    val frameDuration = gifDrawable.getFrameDuration(i).toLong()
                    time += frameDuration
                    webPAnimEncoder.addFrame(time, resizeBitmap)
                }

                webPAnimEncoder.assemble(BaseApp.mContext, gifDrawable.duration.toLong(), Uri.fromFile(out))
                webPAnimEncoder.release()
```

- originGif
![origin](https://github.com/UdaraWanasinghe/webp-android/assets/7650970/aadca70d-29e6-4f37-932a-09bc445538f3)

- library convert webp in whatsapp 
https://github.com/UdaraWanasinghe/webp-android/assets/7650970/71743d96-b912-4fa0-a318-f9b2344397ab

**Comment by zubinxiong** [comment]
![image](https://github.com/UdaraWanasinghe/webp-android/assets/7650970/6b5acbb1-9f48-420a-83dc-dd2ea0ec788a)

- This is the info using webpinfo tools check, the Dispose seems a lit bit different in some frame

**Comment by UdaraWanasinghe** [comment]
Try changing from `WebPConfig.COMPRESSION_LOSSY` to `WebPConfig.COMPRESSION_LOSSLESS`
**Dispose** is an internally determined parameter by the encoder. See WEBP container specification for more information https://developers.google.com/speed/webp/docs/riff_container#animation

**Comment by zubinxiong** [comment]
- Change to WebPConfig.COMPRESSION_LOSSLESS not work.
- I think the problem maybe the way i generate the anim webp. I use gifDrawable to spilt each frame bitmap and addFrame to webp, some image information maybe lost in this step, like frame blending and disposal

**Comment by UdaraWanasinghe** [comment]
Save the returned bitmaps and verifying them for any distortions or use different gif decoder like Glide.
https://github.com/bumptech/glide

```kotlin
val target = Glide.with(context)
    .asGif()
    .load(srcUri)
    .submit()
val drawable = target.get()
val gifState = drawable.constantState ?: throw NullPointerException("GifState is null")
val frameLoaderField = gifState.javaClass.getDeclaredField("frameLoader")
frameLoaderField.isAccessible = true
val frameLoader = frameLoaderField[gifState]
val decoderField = frameLoader.javaClass.getDeclaredField("gifDecoder")
decoderField.isAccessible = true
val gifDecoder = decoderField[frameLoader] as StandardGifDecoder

for (i in 0 until gifDecoder.frameCount) {
    gifDecoder.advance()
    val bitmap = gifDecoder.nextFrame
}
```

**Comment by zubinxiong** [comment]
- use glide to get bitmap have the same problem
- I am trying other way to generate the webp picture by set every frame offsetx and offsety to 0, width and height always 512 like the origin gif, this problem can solve
