### ISSUE TITLE
Could not find com.aureusapps.gradle:plugin-utils:1.0.0.

### ISSUE THREAD

**Issue by SkeletonKing-SNK** [UdaraWanasinghe/webp-android#6]
mavenLocal()
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url = uri("https://maven.aliyun.com/nexus/content/groups/public/") }
        maven { url = uri("https://maven.aliyun.com/nexus/content/repositories/releases/") }
        maven { url = uri("https://jitpack.io") }

Could not resolve all artifacts for configuration 'classpath'.
> Could not find com.aureusapps.gradle:plugin-utils:1.0.0.
  Searched in the following locations:
    - file:/C:/Users/admin/.m2/repository/com/aureusapps/gradle/plugin-utils/1.0.0/plugin-utils-1.0.0.pom
    - https://plugins.gradle.org/m2/com/aureusapps/gradle/plugin-utils/1.0.0/plugin-utils-1.0.0.pom
    - https://maven.aliyun.com/nexus/content/groups/public/com/aureusapps/gradle/plugin-utils/1.0.0/plugin-utils-1.0.0.pom
    - https://maven.aliyun.com/nexus/content/repositories/releases/com/aureusapps/gradle/plugin-utils/1.0.0/plugin-utils-1.0.0.pom
    - https://jitpack.io/com/aureusapps/gradle/plugin-utils/1.0.0/plugin-utils-1.0.0.pom
  Required by:
      unspecified:unspecified:unspecified
尝试了多种添加都找不到这个库。

**Comment by ghost** [comment]
这个是demo代码提示的

**Comment by UdaraWanasinghe** [comment]
我正在使用非公共构建脚本 API。 请将示例应用程序模块复制到新项目中以运行它。
