### ISSUE TITLE
import com.aureusapps.android.webpandroid.encoder.WebPAnimEncoder

### ISSUE THREAD

**Issue by SkeletonKing-SNK** [UdaraWanasinghe/webp-android#7]
implementation "com.aureusapps.android:webp-android:1.0.6"

提示
D:\AndroidStudioProjects\lemi\cardpro_android\app\src\main\java\vip\invit\anna\mvp\ui\MainActivity.java:53: ����: �޷�����WebPAnimEncoder
import com.aureusapps.android.webpandroid.encoder.WebPAnimEncoder;
                                                 ^
  ��������ļ�: C:\Users\admin\.gradle\caches\transforms-3\0a381e725ae67a363c0d623d2d6926f8\transformed\jetified-webp-android-1.0.6-api.jar(/com/aureusapps/android/webpandroid/encoder/WebPAnimEncoder.class)
    ���ļ����д���İ汾 61.0, ӦΪ 55.0
    ��ɾ�����ļ���ȷ�����ļ�λ����ȷ����·����Ŀ¼�С�

**Comment by UdaraWanasinghe** [comment]
你的问题不清楚
